export const ON_ADD_EMAIL_TO_NEWSLETTER_SUCCEEDED = "ON_ADD_EMAIL_TO_NEWSLETTER_SUCCEEDED";
export const ON_ADD_EMAIL_TO_NEWSLETTER_FAILED = "ON_ADD_EMAIL_TO_NEWSLETTER_FAILED";

export const ON_SUBSCRIBE_STOCKOUT_SUCCEEDED = "ON_SUBSCRIBE_STOCKOUT_SUCCEEDED";
export const ON_SUBSCRIBE_STOCKOUT_FAILED = "ON_SUBSCRIBE_STOCKOUT_FAILED";

export const ON_CLEAN_ERRORS_NEWSLETTER = "ON_CLEAN_ERRORS_NEWSLETTER";
export const ON_CLEAN_ERRORS_STOCKOUT = "ON_CLEAN_ERRORS_STOCKOUT";