export const ON_GET_PRODUCT_SUCCEEDED = 'ON_GET_PRODUCT_SUCCEEDED';
export const ON_GET_PRODUCT_FAILED = 'ON_GET_PRODUCT_FAILED';

export const ON_GET_HOME_RELATED_PRODUCTS_SUCCEEDED = 'ON_GET_HOME_RELATED_PRODUCTS_SUCCEEDED';
export const ON_GET_HOME_RELATED_PRODUCTS_FAILED = 'ON_GET_HOME_RELATED_PRODUCTS_FAILED';

export const ON_GET_NEW_RELATED_PRODUCTS_SUCCEEDED = 'ON_GET_NEW_RELATED_PRODUCTS_SUCCEEDED';
export const ON_GET_NEW_RELATED_PRODUCTS_FAILED = 'ON_GET_NEW_RELATED_PRODUCTS_FAILED';

export const ON_GET_RELATED_PRODUCTS_SUCCEEDED = 'ON_GET_RELATED_PRODUCTS_SUCCEEDED';
export const ON_GET_RELATED_PRODUCTS_FAILED = 'ON_GET_RELATED_PRODUCTS_FAILED';

export const ON_GET_DEFAULT_PRODUCTS_SUCCEEDED = 'ON_GET_DEFAULT_PRODUCTS_SUCCEEDED';
export const ON_GET_DEFAULT_PRODUCTS_FAILED = 'ON_GET_DEFAULT_PRODUCTS_FAILED';

export const ON_GET_SHIPPING_TIME_SUCCEEDED = 'ON_GET_SHIPPING_TIME_SUCCEEDED';
export const ON_GET_SHIPPING_TIME_FAILED = 'ON_GET_SHIPPING_TIME_FAILED';