export const ON_GET_CART_LOADING_START = 'ON_GET_CART_LOADIND_START';
export const ON_GET_CART_LOADING_FINISHED = 'ON_GET_CART_LOADING_FINISHED';
export const ON_ADD_TO_CART_LOADING_START = 'ON_ADD_TO_CART_LOADING_START';
export const ON_ADD_TO_CART_LOADING_FINISHED = 'ON_ADD_TO_CART_LOADING_FINISHED';
export const ON_UPDATE_TO_CART_LOADING_START = 'ON_UPDATE_TO_CART_LOADING_START';
export const ON_UPDATE_TO_CART_LOADING_FINISHED = 'ON_UPDATE_TO_CART_LOADING_FINISHED';
export const ON_DELETE_TO_CART_LOADING_START = 'ON_DELETE_TO_CART_LOADING_START';
export const ON_DELETE_TO_CART_LOADING_FINISHED = 'ON_DELETE_TO_CART_LOADING_FINISHED';
export const ON_ADD_COUPON_LOADING_START = 'ON_ADD_COUPON_LOADING_START';
export const ON_ADD_COUPON_LOADING_FINISHED = 'ON_ADD_COUPON_LOADING_FINISHED';
export const ON_DELETE_COUPON_LOADING_START = 'ON_DELETE_COUPON_LOADING_START';
export const ON_DELETE_COUPON_LOADING_FINISHED = 'ON_DELETE_COUPON_LOADING_FINISHED';
export const ON_CALC_SHIPPING_COST_LOADING_START = 'ON_CALC_SHIPPING_COST_LOADING_START';
export const ON_CALC_SHIPPING_COST_LOADING_FINISHED = 'ON_CALC_SHIPPING_COST_LOADING_FINISHED';
export const ON_EMPTY_CART_LOADING_START = 'ON_EMPTY_CART_LOADING_START';
export const ON_EMPTY_CART_LOADING_FINISHED = 'ON_EMPTY_CART_LOADING_FINISHED';
export const ON_START_BUY_LOADING_START = 'ON_START_BUY_LOADING_START';
export const ON_START_BUY_LOADING_FINISHED = 'ON_START_BUY_LOADING_FINISHED';
export const ON_GET_ORDER_LOADING_START = 'ON_GET_ORDER_LOADIND_START';
export const ON_GET_ORDER_LOADING_FINISHED = 'ON_GET_ORDER_LOADING_FINISHED';

export const ON_SUBSCRIBE_STOCKOUT_LOADING_START = 'ON_SUBSCRIBE_STOCKOUT_LOADING_START';
export const ON_SUBSCRIBE_STOCKOUT_LOADING_FINISHED = 'ON_SUBSCRIBE_STOCKOUT_LOADING_FINISHED';

export const ON_NEWSLETTER_LOADING_START = 'ON_NEWSLETTER_LOADING_START';
export const ON_NEWSLETTER_LOADING_FINISHED = 'ON_NEWSLETTER_LOADING_FINISHED';